export const ADD_COMMENT = 'ADD_COMMENT';
export const PHOTOS_LOADING = 'PHOTOS_LOADING';
export const PHOTOS_FAILED = 'PHOTOS_FAILED';
export const ADD_PHOTOS = 'ADD_PHOTOS';
export const ADD_COMMENTS = 'ADD_COMMENTS';
export const COMMENTS_FAILED = 'COMMENTS_FAILED';